- frontend/src/casedata/components/errand/sidebar/sidebar-generic-notes.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-generic-notes.component.tsx
> draken-593 feature: changed remove comment icon

- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
> uf-9952 feature: restricted close errand button

- frontend/src/casedata/components/errand/tabs/contract/casedata-contract-tab.tsx
- frontend/src/casedata/services/contract-service.ts
> small fixes in layout

- frontend/src/common/components/layout/layout.component.tsx
> draken-592 feature: added color and icon for internal response status label

- backend/src/controllers/casedata/casedata-appeal.controller.ts
- backend/src/controllers/casedata/casedata-attachment.controller.ts
- backend/src/controllers/casedata/casedata-errand.controller.ts
- backend/src/controllers/casedata/casedata-facilities.controller.ts
- backend/src/controllers/casedata/casedata-history.controller.ts
- backend/src/controllers/casedata/casedata-notes.controller.ts
- backend/src/controllers/casedata/casedata-stakeholder.controller.ts
- backend/src/controllers/message.controller.ts
- backend/src/controllers/supportmanagement/support-errand.controller.ts
- backend/src/data-contracts/case-data/data-contracts.ts
- backend/src/data-contracts/supportmanagement/data-contracts.ts
- backend/src/interfaces/attachment.interface.ts
- backend/src/interfaces/decision.interface.ts
- backend/src/interfaces/errand-note.interface.ts
- backend/src/interfaces/errand-status.interface.ts
- backend/src/interfaces/errand.interface.ts
- backend/src/interfaces/stakeholder.interface.ts
- backend/src/services/contract-service.ts
- backend/src/services/errand.service.ts
- backend/src/services/message.service.ts
- backend/src/services/stakeholder.service.ts
- backend/src/swagger-typescript-api.ts
> Update data contracts (NOTE ExtraParameters logic still broken)

- backend/src/controllers/casedata/casedata-notes.controller.ts
- backend/src/services/errand.service.ts
- frontend/src/casedata/services/casedata-errand-notes-service.ts
- frontend/src/casedata/services/casedata-history-service.ts
> Adjust notes endpoints

- backend/src/controllers/casedata/casedata-errand.controller.ts
- backend/src/controllers/casedata/casedata-stakeholder.controller.ts
- backend/src/interfaces/errand.interface.ts
- backend/src/services/api.service.ts
- backend/src/services/stakeholder.service.ts
- frontend/src/casedata/interfaces/errand.ts
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/casedata/services/casedata-history-service.ts
- frontend/src/casedata/services/casedata-stakeholder-service.ts
- frontend/src/common/data-contracts/case-data/data-contracts.ts
> Stakeholder endpoints

- frontend/src/casedata/components/casedata-filtering/casedata-filtering.component.tsx
- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-query.component.tsx
- frontend/src/casedata/components/ongoing-casedata-errands/ongoing-casedata-errands.component.tsx
- frontend/src/common/components/layout/layout.component.tsx
> Layout with page header for MEX/PT

- backend/src/controllers/casedata/casedata-facilities.controller.ts
- frontend/cypress/e2e/case-data/mex/errandPage-errand-info-tab-mex.cy.ts
- frontend/cypress/e2e/case-data/pt/errandPage-errand-info-tab-pt.cy.ts
- frontend/src/casedata/services/casedata-facilities-service.ts
> changing endpoints for facilities

- backend/src/controllers/supportmanagement/support-errand.controller.ts
- backend/src/interfaces/errand.interface.ts
- backend/src/services/contract-service.ts
- backend/src/services/errand.service.ts
- frontend/cypress/e2e/case-data/fixtures/mockMexErrand.ts
- frontend/cypress/e2e/case-data/fixtures/mockPtErrand.ts
- frontend/cypress/e2e/case-data/mex/errandPage-errand-details-tab-mex.cy.ts
- frontend/cypress/e2e/case-data/pt/errandPage-errand-details-tab-pt.cy.ts
- frontend/src/casedata/components/errand/phasechanger/phasechanger.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
- frontend/src/casedata/components/errand/tabs/decision/casedata-decision-tab.tsx
- frontend/src/casedata/components/errand/tabs/details/casedata-details-tab.tsx
- frontend/src/casedata/hooks/displayPhasePoller.ts
- frontend/src/casedata/interfaces/errand.ts
- frontend/src/casedata/interfaces/extra-parameters.ts
- frontend/src/casedata/services/casedata-attachment-service.ts
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/casedata/services/casedata-extra-parameters-service.ts
- frontend/src/casedata/services/contract-service.ts
> Handle new format of extraParameters

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
> Do not use message type for Parking permit

- frontend/src/supportmanagement/components/ongoing-support-errands/components/supporterrands-table.component.tsx
> uf-10625 fix: extended trigger setting of sidebar buttons

- frontend/src/casedata/components/errand/tabs/contract/kopeavtal.tsx
- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
Disclosure-komponenten vill ha ikon-komponenter för att rätt visa dem.
> Pass icon components, not strings, to Disclosure

- backend/src/services/message.service.ts
> Use namespace and correct api version

- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
- frontend/src/casedata/components/errand/tabs/contract/kopeavtal.tsx
- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
- frontend/src/casedata/components/errand/tabs/overview/casedata-contacts.component.tsx
- frontend/src/casedata/interfaces/role.ts
- frontend/src/casedata/services/casedata-stakeholder-service.ts
> Use separate relations for PT

- frontend/src/casedata/components/errand/phasechanger/phasechanger.component.tsx
- frontend/src/casedata/services/casedata-attachment-service.ts
- frontend/src/casedata/services/casedata-errand-service.ts
> Validate attachments before going to phase Beslut

- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
Phone and email not mandatory for now.
> Allow manually adding stakeholder also for PT.

- frontend/src/casedata/components/errand/tabs/contract/kopeavtal.tsx
- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
> Fix build errors

- frontend/src/supportmanagement/services/support-errand-service.ts
> Handle filtering for labelTypes without labelSubTypes

- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
> No nested ps

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
> Do not use message type for PT

- backend/src/controllers/address.controller.ts
- backend/src/controllers/casedata/casedata-facilities.controller.ts
- backend/src/controllers/message.controller.ts
- backend/src/controllers/supportmanagement/support-facilities.controller.ts
- backend/src/services/message.service.ts
- frontend/src/casedata/components/errand/casedata-errand.component.tsx
- frontend/src/casedata/components/errand/tabs/messages/casedata-messages-tab.tsx
- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
- frontend/src/casedata/components/errand/tabs/messages/rendered-message.component.tsx
- frontend/src/casedata/services/casedata-message-service.ts
- frontend/src/common/interfaces/message.ts
- frontend/tailwind.config.ts
Spara skickat meddelande på ärende. Sätt viewed=true direkt. Använd datamodell från API, inte hemsnickrat.
> Save message on errand. Use actual data contract from API.

- backend/src/interfaces/errand-status.interface.ts
- frontend/src/casedata/components/ongoing-casedata-errands/components/errands-table.component.tsx
- frontend/src/casedata/interfaces/errand-status.ts
- frontend/src/casedata/services/casedata-errand-service.ts
> Enable sorting for some PT table columns

- frontend/src/casedata/components/errand/tabs/overview/casedata-contacts.component.tsx
> Render all stakeholders, even if they do not have role CONTACT_PERSON

- frontend/src/casedata/components/errand/tabs/decision/casedata-decision-tab.tsx
- frontend/src/casedata/services/casedata-message-service.ts
> Handle messages to OpenE

- frontend/src/casedata/components/errand/tabs/attachments/casedata-attachments.component.tsx
- frontend/src/casedata/services/casedata-attachment-service.ts
> Use same upload component for PT as for MEX

- backend/src/controllers/supportmanagement/support-errand.controller.ts
- frontend/src/supportmanagement/components/new-contacts/support-contacts.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
> Handle additional roles

- frontend/src/casedata/components/errand/tabs/permits-services/casedata-permits-services-tab.tsx
> added space between date.

- frontend/src/casedata/components/ongoing-casedata-errands/components/casedata-status-label.component.tsx
- frontend/src/casedata/components/ongoing-casedata-errands/components/errands-table.component.tsx
> Use status label component similar to LOP/KS in MEX/PT

- frontend/src/common/components/main-errands-sidebar/main-errands-sidebar.component.tsx
- frontend/src/common/services/feature-flag-service.ts
> Hide MEX/PT notifications in prod environment

- frontend/src/casedata/services/casedata-attachment-service.ts
Require passport photo and medical confirmation only for new parking permits
> Attachment validation changes

- frontend/src/supportmanagement/components/new-contacts/support-contacts.component.tsx
- frontend/src/supportmanagement/components/new-contacts/support-simplified-contact-form.component.tsx
- frontend/src/supportmanagement/components/support-errand-basics-form/support-errand-basics-about-form.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/request-info.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/request-internal.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
- frontend/src/supportmanagement/components/support-errand/support-tabs-wrapper.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/messages/support-messages-tab.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-basics-tab.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
- frontend/src/supportmanagement/services/support-escalation-service.ts
Uppdatera meddelandemallar för IK och justera funktionalitet per app.
> Update message templates and some feature flags

- frontend/src/casedata/services/casedata-errand-service.ts
JIra: https://jira.sundsvall.se/browse/DRAKEN-712
> Remove empty extraParameters.

- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
> pt-does-not-require-email-or-tele

- frontend/src/casedata/components/errand/tabs/decision/casedata-decision-tab.tsx
> changed-showConfirmation-color-from-green-to-blue

- frontend/src/supportmanagement/services/support-errand-service.ts
> cannot delete stakeholders

- frontend/src/casedata/components/ongoing-casedata-errands/components/errands-table.component.tsx
> added new width to column 'Ärendetyp'

- frontend/src/common/components/layout/layout.component.tsx
> Show errand number also in PT

- frontend/src/supportmanagement/components/support-errand/sidebar/close-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-history.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
- frontend/src/supportmanagement/services/support-message-service.ts
- frontend/src/supportmanagement/services/support-revision-service.ts
Lägg till lösningskoder för IK.
Fixa ärendehistoriken så inte en massa ändringar visas som "Ej implementerad"
> Add IK resolution codes and fix history service

- frontend/src/casedata/components/errand/tabs/decision/casedata-decision-tab.tsx
> changed validation of decision.

- backend/src/controllers/supportmanagement/support-message.controller.ts
- backend/src/services/api.service.ts
- frontend/src/supportmanagement/components/new-contacts/support-contacts.component.tsx
- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
- frontend/src/supportmanagement/services/support-message-service.ts
> OpenE messages for KS/LOP

- frontend/src/casedata/components/errand/casedata-errand.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-513
> added facilities in header.

- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
> added check for PT

- README.md
- backend/src/controllers/address.controller.ts
> bump version and added municipalityId in request!

- frontend/src/supportmanagement/services/support-message-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-779
> added message for IK

- .gitignore
- backend/src/controllers/supportmanagement/support-errand.controller.ts
- backend/src/interfaces/support-contactchannel.ts
- frontend/src/common/components/commonNestedEmailArrayV2.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
- frontend/src/supportmanagement/services/support-escalation-service.ts
- frontend/src/supportmanagement/services/support-message-service.ts
- frontend/src/supportmanagement/services/support-stakeholder-service.ts
Övergå till nycklar med stora bokstäver för kontaktvägar (dvs EMAIL, PHONE istället för som tidigare Email, Phone).
Anledningen är att backend/API använder EMAIL/PHONE när stakeholders skapas ifrån inkommande epost. Stora bokstäver är det rimliga valet för nyckelvärden, och det har konstaterats att det enklaste sättet att hantera detta plus all existerande data är att frontend jobbar med båda nyckelvärden (dvs både EMAIL och Email), tills man om en tid kan frångå Email helt.
> Move to all uppercase keys

- backend/src/interfaces/errand-status.interface.ts
- backend/src/interfaces/errand.interface.ts
- backend/src/services/errand.service.ts
- frontend/cypress/e2e/case-data/mex/errandPage-sidebar-mex.cy.ts
- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-sidebarstatus-selector.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
- frontend/src/casedata/components/suspend-errand.tsx
- frontend/src/casedata/interfaces/errand-status.ts
- frontend/src/casedata/interfaces/errand.ts
- frontend/src/casedata/services/casedata-errand-service.ts
Jira: https://jira.sundsvall.se/browse/UF-10637
> Added-parking-to-casedata

- frontend/src/casedata/components/errand/tabs/attachments/casedata-attachments.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-attachments-tab.tsx
Samt datum på bilagor i supportmanagement
Jira: https://jira.sundsvall.se/browse/DRAKEN-538
> Klickbara bilagor

- frontend/src/supportmanagement/services/support-errand-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-802
> changed label

- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-683
> added ability to change status when sending message.

- frontend/src/supportmanagement/services/support-errand-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-807
> Hämtar endast parkerade ärenden

- frontend/src/casedata/components/errand/sidebar/sidebar-generic-notes.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-generic-notes.component.tsx
Gäller både supportmanagement och casedata
Jira: https://jira.sundsvall.se/browse/DRAKEN-202
> Ej möjligt att skriva kommentarer på avslutade ärenden

- backend/src/services/api.service.ts
- backend/src/services/contract-service.ts
- frontend/src/casedata/components/errand/tabs/contract/casedata-contract-tab.tsx
> Add missing namespace to contract validation request

- frontend/src/casedata/components/suspend-errand.tsx
Jira: https://jira.sundsvall.se/browse/UF-11394
> stängt av parkera knappen vid fasbyte eller om ärendet är avslutat

- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-details-tab.tsx
> Group sick note dates in details by string matching

- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
- frontend/src/common/services/helper-service.ts
- frontend/src/supportmanagement/components/new-contacts/support-simplified-contact-form.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-810
> Tagit bort placeholder och gjort om label

- frontend/next-env.d.ts
- frontend/package.json
- frontend/yarn.lock
Testa gärna igenom olika steg och faser i draken för att se om allt fungerar.
> bumb next from 14.1.1 --> 14.2.10

- frontend/src/casedata/components/errand/tabs/overview/casedata-contacts.component.tsx
Jira: https://jira.sundsvall.se/browse/UF-11401
> Rundade hörn för kontaktkort

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
- frontend/src/casedata/services/casedata-message-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-646
> Sparar bilagor som laddats upp från meddelande

- backend/src/controllers/supportmanagement/support-errand.controller.ts
- frontend/cypress/e2e/kontaktcenter/errandPage-sidebar-kc.cy.ts
- frontend/cypress/e2e/kontaktcenter/fixtures/mockForwardSupportMessage.ts
- frontend/src/supportmanagement/services/support-errand-service.ts
Jira: https://jira.sundsvall.se/browse/UF-11481
> hantering för organisationsnamn samt cypress test

- frontend/src/casedata/services/contract-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-848
> changed position for free text condition in pdf

- frontend/cypress/e2e/case-data/mex/errandPage-contracts-tab-landLease-mex.cy.ts
- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
- [] Bug fix
Jira: https://jira.sundsvall.se/browse/DRAKEN-845
> minor adjustment to conditons text

- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
Jira: 
https://jira.sundsvall.se/browse/DRAKEN-832
https://jira.sundsvall.se/browse/DRAKEN-830
https://jira.sundsvall.se/browse/DRAKEN-821
https://jira.sundsvall.se/browse/DRAKEN-836
https://jira.sundsvall.se/browse/DRAKEN-838
> text changes

- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-828
> changes to rental fee section

- frontend/next-env.d.ts
- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
> Build errors

- backend/src/controllers/message.controller.ts
- backend/src/services/message.service.ts
> Bump to Messaging 6.0

- frontend/src/casedata/services/contract-render-service.tsx
- frontend/src/casedata/services/contract-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-825
> useEffect to initalize value of checkbox items

- frontend/src/casedata/services/contract-render-service.tsx
> Fix build error

- frontend/src/supportmanagement/components/support-errand/tabs/messages/support-messages-tab.tsx
PR till main, finns en tvilling till develop (pga brytande API-diff mellan prod och test i nuläget): https://github.com/Sundsvallskommun/web-app-draken-public/pull/160
> Update email and sms template for KS

- frontend/cypress/e2e/case-data/mex/errandPage-contracts-tab-landLease-mex.cy.ts
- frontend/src/casedata/components/errand/tabs/contract/contract-navigation.tsx
- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
- frontend/src/casedata/services/contract-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-844
> changed header text for contract section

- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-900
> .Feature/draken-900-text-changes

- backend/src/controllers/supportmanagement/support-notification-controller.ts
> HOTFIX Add globalAcknowledged to notification DTO

- frontend/next-env.d.ts
- frontend/src/supportmanagement/components/support-errand/tabs/messages/support-messages-tab.tsx
> disabling new message - button if status is NEW 'Inkommet'

- frontend/src/common/components/main-errands-sidebar/main-errands-sidebar.component.tsx
- frontend/src/common/services/feature-flag-service.ts
- frontend/src/supportmanagement/components/ongoing-support-errands/ongoing-support-errands.component.tsx
> checks if user have access to billingrecords

- frontend/src/casedata/components/errand/tabs/contract/kopeavtal.tsx
- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
- frontend/src/casedata/interfaces/kopeavtals-data.ts
- frontend/src/casedata/interfaces/lagenhetsarrende-data.ts
- frontend/src/casedata/services/contract-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-849
> changed signature appearance for both contracts

- frontend/cypress/e2e/case-data/mex/errandPage-contracts-tab-landLease-mex.cy.ts
- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
- frontend/src/casedata/interfaces/lagenhetsarrende-data.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-864
Saknas värde för 2025. Detta måste läggas till när det finns från SCB.
> changes to rental fee

- frontend/cypress/e2e/case-data/fixtures/mockAttachments.ts
- frontend/src/casedata/services/casedata-attachment-service.ts
> Fix type error

- frontend/src/casedata/interfaces/case-label.ts
> Adjust to fixed typos in API

- backend/src/controllers/casedata/casedata-notification-controller.ts
- frontend/src/casedata/services/casedata-notification-service.ts
- frontend/src/common/data-contracts/case-data/data-contracts.ts
- frontend/src/data-contracts/backend/data-contracts.ts
> Add errandId to patch request

- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-sidebarstatus-selector.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
> Featureflag disable suspension of casedata errands

- frontend/next-env.d.ts
- frontend/src/casedata/components/errand/phasechanger/phasechanger.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
Reverts Sundsvallskommun/web-app-draken-public#182
> Revert "Feature/draken 908 handle phase uppfoljning"

- frontend/src/supportmanagement/services/support-message-service.ts
> changing data conditions so right data is sent based on contact means

- frontend/next-env.d.ts
En autogenererad fil som ändrats.
> Add autogenerated file

- frontend/src/casedata/services/casedata-errand-service.ts
> Status = Tilldelat is not cause for locking errand.

- frontend/src/casedata/components/errand/phasechanger/phasechanger.component.tsx
Justera hantering av faser och status för när Avsluta ärende-knapp ska visas.
> Show Avsluta-knapp in phase uppfoljning

- frontend/src/casedata/interfaces/role.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-936
> updates to roles

- frontend/src/casedata/components/ongoing-casedata-errands/components/errands-table.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-811
> added errandnumber to errand overview page

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-644
> default signature for messages in casedata

- frontend/src/casedata/components/errand/tabs/details/casedata-details-tab.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-details-tab.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-984
> show opene id for casedata and supportmanagement

- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-attachments-tab.tsx
> Do not show timestamp

- backend/src/controllers/address.controller.ts
- backend/src/controllers/supportmanagement/support-attachment.controller.ts
- backend/src/controllers/supportmanagement/support-errand.controller.ts
- backend/src/controllers/supportmanagement/support-facilities.controller.ts
- backend/src/controllers/supportmanagement/support-history.controller.ts
- backend/src/controllers/supportmanagement/support-message.controller.ts
- backend/src/controllers/supportmanagement/support-metadata.controller.ts
- backend/src/controllers/supportmanagement/support-note.controller.ts
- backend/src/controllers/supportmanagement/support-notification-controller.ts
- backend/src/services/support-errand.service.ts
> Bump to supportmanagement 9 and businessengagements 3.0

- frontend/cypress/e2e/case-data/mex/errandPage-base-info-tab-mex.cy.ts
- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
- frontend/src/casedata/interfaces/contracts.ts
- frontend/src/casedata/interfaces/stakeholder.ts
- frontend/src/casedata/services/casedata-stakeholder-service.ts
- frontend/src/casedata/services/contract-service.ts
> added extra information for stakeholders in mex

- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
> change sender name for emails in kc

- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-866
> changed styling

- frontend/src/pages/_app.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1017
> get colorscheme from store

- frontend/src/casedata/components/errand/tabs/details/casedata-details-tab.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1018
> changed to textarea from web-shared-components

- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1020
> fix for error when writing self-written terms

- frontend/src/supportmanagement/services/support-errand-service.ts
> Use municipality id from env

- frontend/src/casedata/components/errand/tabs/attachments/casedata-attachments.component.tsx
Jira: https://jira.sundsvall.se/browse/UF-14615
> fix for downloaidng msg attachments

- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
> removed unused import

- frontend/src/casedata/components/errand/tabs/attachments/casedata-attachments.component.tsx
> Fix conflict

- frontend/cypress/e2e/kontaktcenter/errandPage-sidebar-kc.cy.ts
- frontend/src/supportmanagement/components/support-errand/sidebar/close-errand.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-893
> removed solution code for ks

- frontend/package.json
- frontend/yarn.lock
Jira: https://jira.sundsvall.se/browse/DRAKEN-1033
> updated cypress version

- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-1019
> feat: escalate to multiple emails in supportmanagement

- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-sidebarstatus-selector.component.tsx
> feat: enable suspended errands to be viewed in sidebar

- backend/src/controllers/casedata/casedata-errand.controller.ts
> bug: fix for filter errands using status in casedata

- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1051
> feat: show answer button for open e messages

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1045
https://jira.sundsvall.se/browse/DRAKEN-1046
https://jira.sundsvall.se/browse/DRAKEN-1050
> feat: changes to messages in casedata and supportmangement

- README.md
- backend/src/controllers/billing.controller.ts
- backend/src/data-contracts/billingpreprocessor/data-contracts.ts
- backend/src/interfaces/billing-interface.ts
- backend/src/swagger-typescript-api.ts
- frontend/src/data-contracts/backend/data-contracts.ts
- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-invoice-tab.tsx
- frontend/src/supportmanagement/services/support-billing-service.ts
Gå upp till BillingPreprocessor 4.0
> Adapt to BPP 4.0

- backend/src/controllers/supportmanagement/support-errand.controller.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-1076
> filtering multiple priorities

- backend/src/controllers/estateInfo.controller.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-1043
> feat: update estateinfo version

- frontend/cypress/e2e/case-data/mex/oversikt.cy.ts
- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-sidebarstatus-selector.component.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/common/components/layout/sidebar-layout.component.tsx
- frontend/src/common/components/main-errands-sidebar/main-errands-sidebar.component.tsx
- frontend/src/supportmanagement/components/supportmanagement-filtering/components/supportmanagement-filter-sidebarstatus-selector.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-584
> hide sidebar i startview

- frontend/src/casedata/components/errand/tabs/decision/casedata-decision-tab.tsx
- frontend/src/casedata/components/errand/tabs/details/casedata-details-tab.tsx
- frontend/src/casedata/components/errand/tabs/overview/casedata-form.component.tsx
- frontend/src/casedata/services/casedata-extra-parameters-service.ts
Jira; https://jira.sundsvall.se/browse/DRAKEN-1044
> form for errand information for casetype appeal

- README.md
- backend/src/controllers/supportmanagement/support-attachment.controller.ts
- backend/src/controllers/supportmanagement/support-errand.controller.ts
- backend/src/controllers/supportmanagement/support-facilities.controller.ts
- backend/src/controllers/supportmanagement/support-history.controller.ts
- backend/src/controllers/supportmanagement/support-message.controller.ts
- backend/src/controllers/supportmanagement/support-metadata.controller.ts
- backend/src/controllers/supportmanagement/support-note.controller.ts
- backend/src/controllers/supportmanagement/support-notification-controller.ts
- backend/src/data-contracts/supportmanagement/data-contracts.ts
- backend/src/services/support-errand.service.ts
- backend/src/swagger-typescript-api.ts
- frontend/package.json
- frontend/src/common/interfaces/message.ts
- frontend/src/data-contracts/backend/data-contracts.ts
- frontend/src/supportmanagement/components/save-button/save-button.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-details-tab.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
- frontend/src/supportmanagement/services/support-message-service.ts
Gå upp till Supportmanagement v10.0 och anpassningar därefter. Berör alltså KS, LOP och IK.
För att testa: kolla så att ärendebilagor och meddelandebilagor fungerar att bifoga, ladda upp och ladda ner/öppna.
> Adapt to SM10 attachment handling, along with updating data contracts.

- backend/src/controllers/supportmanagement/support-errand.controller.ts
> More validation errors

- frontend/src/supportmanagement/components/attestation-tab/attestation-tab.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1116
> fixed pagination for billingrecords

- backend/src/controllers/supportmanagement/support-errand.controller.ts
> Fix escalation bug

- frontend/src/casedata/components/ongoing-casedata-errands/components/errands-table.component.tsx
- frontend/src/supportmanagement/components/ongoing-support-errands/components/supporterrands-table.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1090
> removed callout for globalacknowledged notifications

- frontend/src/casedata/components/casedata-filtering/casedata-filtering.component.tsx
- frontend/src/supportmanagement/components/attestation-tab/components/attestation-filtering/attestations-filtering.component.tsx
- frontend/src/supportmanagement/components/supportmanagement-filtering/supportmanagement-filtering.component.tsx
> Show filters by default

- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-sidebarstatus-selector.component.tsx
- frontend/src/common/components/main-errands-sidebar/main-errands-sidebar.component.tsx
- frontend/src/supportmanagement/components/supportmanagement-filtering/components/supportmanagement-filter-sidebarstatus-selector.component.tsx
> changing 99+ to 999+ on status badges main sidebar

- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
> Show ASSIGNED, SOLVED and SUSPENDED in status dropdown

- frontend/src/casedata/components/errand/appeal-button.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/common/services/feature-flag-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-1123
https://jira.sundsvall.se/browse/DRAKEN-1122
> text changes and check for errand status error

- frontend/src/common/services/adress-service.ts
> Null handling for address search

- frontend/src/supportmanagement/services/support-escalation-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-1152
> changed signature for kc

- frontend/src/supportmanagement/components/support-errand/sidebar/request-info.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/messages/support-messages-tab.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1093
> removed text from email template

- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
> Remove doubled status

- frontend/src/common/components/layout/sidebar-layout.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1173
> bugfix for filter getting cut off

- frontend/cypress/e2e/kontaktcenter/errandPage-sidebar-kc.cy.ts
- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
> FIx email validation error in forward form.

- frontend/src/supportmanagement/components/support-errand-basics-form/support-errand-basics-about-form.component.tsx
> Change select label for Kontakt Ånge

- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
Även Kontakt Ånge ska kunna vidarebefordra ärenden via e-post.
> Enable email forwarding in Kontakt Ånge

- backend/src/controllers/supportmanagement/support-errand.controller.ts
> Change default classification for Kontakt Ånge

- backend/src/controllers/address.controller.ts
- frontend/src/common/services/adress-service.ts
> Fix employee personnumber search due to changed API endpoint.

- frontend/src/supportmanagement/components/support-errand-basics-form/support-errand-basics-about-form.component.tsx
- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
> Build error

- frontend/src/common/services/feature-flag-service.ts
- frontend/src/supportmanagement/components/support-errand/support-tabs-wrapper.tsx
> enable billing for prod

- frontend/src/supportmanagement/services/invoiceSettings.ts
Merga tillägget i hårdkodad data även till prod. (Finns redan i test.)
> Add project to internal invoices

- frontend/src/supportmanagement/services/support-stakeholder-service.ts
> Do not send orgnumber as empty string if it is undefined

- frontend/src/supportmanagement/services/support-stakeholder-service.ts
> Sync with main

- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-details-tab.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1293
> fix for darkmode

- frontend/src/casedata/components/errand/tabs/details/casedata-details-tab.tsx
- frontend/src/casedata/services/casedata-extra-parameters-service.ts
> feature: added field for ynumber

- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
> Do not truncate message body on "Från" but on "Från: "

- backend/src/controllers/export.controller.ts
- frontend/cypress/e2e/case-data/fixtures/mockSidebarButtons.ts
- frontend/cypress/e2e/case-data/mex/errandPage-sidebar-mex.cy.ts
- frontend/cypress/e2e/case-data/mex/oversikt.cy.ts
- frontend/src/casedata/components/errand/sidebar/sidebar.wrapper.tsx
- frontend/src/common/components/export-button/export-button.component.tsx
- frontend/src/common/components/export/sidebar-export/sidebar-export.component.tsx
- frontend/src/common/components/sidebar/sidebar.component.tsx
- frontend/src/common/services/export-service.ts
> draken-1059 feature: individual errand export

- backend/src/controllers/export.controller.ts
- backend/src/server.ts
- frontend/cypress/e2e/case-data/fixtures/mockSidebarButtons.ts
- frontend/cypress/e2e/case-data/mex/errandPage-sidebar-mex.cy.ts
- frontend/cypress/e2e/case-data/mex/oversikt.cy.ts
- frontend/src/casedata/components/errand/sidebar/sidebar.wrapper.tsx
- frontend/src/casedata/components/ongoing-casedata-errands/ongoing-casedata-errands.component.tsx
- frontend/src/common/components/export-button/export-button.component.tsx
- frontend/src/common/components/export/sidebar-export/sidebar-export.component.tsx
- frontend/src/common/components/sidebar/sidebar.component.tsx
- frontend/src/common/services/export-service.ts
- frontend/src/common/services/feature-flag-service.ts
> draken-1063 feature: preparation for errand exports

- frontend/src/supportmanagement/services/support-errand-service.ts
> draken-1344 feature: updated KA resolution labels

- README.md
> feat: added rob to readme

- backend/src/controllers/supportmanagement/support-notification-controller.ts
Ta bort validering av notification-body vid patch-anrop (dvs vid acknowledge).
> Remove validation of notification body on patch (acknowledge) request.

- backend/src/controllers/supportmanagement/support-errand.controller.ts
- backend/src/interfaces/support-contactchannel.ts
> feat: simplified filter in backend support errand controller

- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-details-tab.tsx
> Adjust filtering so that all data is shown

- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
> bugfix forwarding errand

- backend/.env.rob.example.local
- backend/src/controllers/supportmanagement/support-errand.controller.ts
> feat: add predefined category for Rob errands

- frontend/public/locales/sv/common.json
- frontend/src/pages/oversikt.tsx
- frontend/src/supportmanagement/components/support-errand-basics-form/support-errand-basics-about-form.component.tsx
- frontend/src/supportmanagement/components/supportmanagement-filtering/components/supportmanagement-filter-category.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
> feat: update labels and translations for ROB app

- frontend/src/supportmanagement/services/support-errand-service.ts
Save contactReasonDescription regardless of selection in contactReason drodown.
> Save contactReasonDescription

- frontend/src/supportmanagement/components/new-contacts/support-contacts.component.tsx
> Look for param: username || userId

- backend/src/services/api.service.ts
Byt namn på headern som innehåller den anropande användarens användarnamn.
> Update tracking header

- frontend/src/common/components/layout/layout.component.tsx
> fix(errand-view): status label for Rob now displays correctly

- frontend/public/locales/sv/common.json
> feat: removed star from filter name

- frontend/src/common/services/helper-service.ts
- frontend/src/supportmanagement/components/ongoing-support-errands/components/supporterrands-table.component.tsx
> feat: add truncate function and apply to errand title

- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
> Do not truncate displayed messages

- frontend/src/supportmanagement/components/ongoing-support-errands/components/supporterrands-table.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
> Show resolution labels for ROB

- frontend/src/casedata/components/save-button/save-button.component.tsx
- frontend/src/casedata/services/casedata-stakeholder-service.ts
Bug fix: Prevented multiple administrators from being saved to the same errand via different save options.
https://jira.sundsvall.se/browse/UF-16083
> bug: multiple admins on same errand

- frontend/src/supportmanagement/services/support-escalation-service.ts
- Added number.
- Removed unused code.
Jira: https://jira.sundsvall.se/browse/DRAKEN-1553
> fe: new phone number for ange for escalation support

- frontend/src/supportmanagement/components/ongoing-support-errands/components/supporterrands-table.component.tsx
> Show status in table, not resolution code

- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-attachments-tab.tsx
> feat: added timestamp uploaded attachments

- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-details-tab.tsx
Justera mappning av parameters för LOP-ärenden. Se https://jira.sundsvall.se/browse/DRAKEN-1346 för exempel på ärenden med data i det nya formatet. (OBS för att se ändringarna behöver man såklart köra denna branch lokalt, och jämföra med tetsmiljön.)
> Adjust parameter mapping

- frontend/src/supportmanagement/services/support-errand-service.ts
Jira: https://jira.sundsvall.se/browse/UF-16000
> feat: remove sort parameter from sidebarUpdatePromises

- backend/src/controllers/casedata/casedata-errand.controller.ts
- backend/src/controllers/supportmanagement/support-errand.controller.ts
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/supportmanagement/services/support-errand-service.ts
Jira: https://jira.sundsvall.se/browse/UF-15202
> fix: only show errands from latest selected filter

- frontend/src/supportmanagement/components/support-errand/sidebar/request-info.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/resume-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/support-errand-details-tab.tsx
- fix for type related crash also included
Jira: https://jira.sundsvall.se/browse/DRAKEN-1615
> fix: added resume errand button to sidebar

- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
> fix: long messages overflowing to other messages

- frontend/src/supportmanagement/components/support-errand/sidebar/message-portal.component.tsx
- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
- Will show update regarding errand status after message is sent.
Jira: https://jira.sundsvall.se/browse/DRAKEN-1614
> fix: updates page after message is sent.

- frontend/src/common/components/notifications/notification-item.tsx
- frontend/src/common/components/notifications/notification-utils.tsx
- Moved logic to utils.
- Changed filter logic to hide all system notifications (Until API is fixed)
- Added comments to indicate the real needs.
Jira: https://jira.sundsvall.se/browse/DRAKEN-1635
> feat: hiding notifications with subtype system/fasbyte

- frontend/src/common/components/notifications/notification-utils.tsx
- Exclude notifications created by current user.
> feat: imroved filter logic for notifications

- frontend/src/supportmanagement/components/support-errand/sidebar/close-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/request-info.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/resume-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
- frontend/src/supportmanagement/services/support-errand-service.ts
- Use primary color for resume button on specific statuses and fallback to secondary for end errand button
Jira: https://jira.sundsvall.se/browse/DRAKEN-1649
> feat: resumeerrand button design changes

- frontend/src/casedata/components/errand/tabs/messages/casedata-messages-tab.tsx
- frontend/src/casedata/components/errand/tabs/messages/rendered-message.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
- Applied both in casedata and supportmanagement namespace.
Jira: https://jira.sundsvall.se/browse/DRAKEN-1654
> feat: name change on receiver on web message

- frontend/src/supportmanagement/components/support-errand/sidebar/close-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/suspend-errand.component.tsx
> Adjust rule for button variant

- frontend/src/app/[locale]/arende/[municipalityId]/[errandNumber]/page.tsx
- frontend/src/app/[locale]/login/page.tsx
- frontend/src/app/[locale]/oversikt/page.tsx
- frontend/src/app/[locale]/registrera/page.tsx
- frontend/src/common/contexts/app.context.tsx
> fix: register new errand redirect to login page

- frontend/public/locales/sv/login.json
- frontend/src/app/[locale]/login/page.tsx
- frontend/src/common/components/empty-layout/empty-layout.component.tsx
> feature: error message for login page

- frontend/src/casedata/components/errand/casedata-errand.component.tsx
- frontend/src/casedata/components/errand/casedata-tabs-wrapper.tsx
- frontend/src/casedata/components/errand/tabs/overview/casedata-form.component.tsx
- frontend/src/casedata/components/save-button/save-button.component.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
> Handle unsaved changes when registering CD errand

- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar.wrapper.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1723
> feat: changed appearance for right sidebar

- frontend/src/casedata/components/errand/tabs/overview/errand-table.component.tsx
- frontend/src/casedata/components/ongoing-casedata-errands/components/casedata-status-label.component.tsx
- frontend/src/common/components/layout/layout.component.tsx
- frontend/src/supportmanagement/components/ongoing-support-errands/components/support-status-label.component.tsx
- frontend/src/supportmanagement/components/ongoing-support-errands/components/supporterrands-table.component.tsx
> fix: refactor status labels for cd and sm

- frontend/src/casedata/components/errand/casedata-tabs-wrapper.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1728
> feat: changed placement for message button

- frontend/cypress/e2e/case-data/mex/errandPage-base-info-tab-mex.cy.ts
- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
- frontend/src/casedata/components/errand/tabs/overview/casedata-contacts.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1729
> feat: text changes for casedata

- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1732
> feat: disable status select if there is no administrator

- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-sidebarstatus-selector.component.tsx
- frontend/src/casedata/components/errand/sidebar/resume-errand-button.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
- frontend/src/casedata/components/suspend-errand.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/support-resume-errand-button.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1733
> fix: button to resume assigned errands in casedata

- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
- frontend/src/casedata/components/suspend-errand.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1742
> feat: update functionality for resumerrandbutton

- backend/src/controllers/relations.controller.ts
- backend/src/controllers/supportmanagement/support-attachment.controller.ts
- backend/src/controllers/supportmanagement/support-conversation.controller.ts
- backend/src/controllers/supportmanagement/support-errand.controller.ts
- backend/src/controllers/supportmanagement/support-facilities.controller.ts
- backend/src/controllers/supportmanagement/support-history.controller.ts
- backend/src/controllers/supportmanagement/support-message.controller.ts
- backend/src/controllers/supportmanagement/support-metadata.controller.ts
- backend/src/controllers/supportmanagement/support-note.controller.ts
- backend/src/controllers/supportmanagement/support-notification-controller.ts
- backend/src/services/support-errand.service.ts
> Bump Supportmanagement to v 10.6

- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1749
> feat: remove dialog for self assign errand in casedata

- frontend/src/app/[locale]/login/page.tsx
- frontend/src/casedata/components/errand/casedata-errand.component.tsx
- frontend/src/casedata/components/ongoing-casedata-errands/ongoing-casedata-errands.component.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/common/components/layout/_app.tsx
- frontend/src/supportmanagement/components/attestation-tab/attestation-tab.component.tsx
- frontend/src/supportmanagement/components/ongoing-support-errands/ongoing-support-errands.component.tsx
- frontend/src/supportmanagement/components/support-errand/support-errand.component.tsx
Småjusteringar av felhantering vid icke inloggad användare.
> Adjust handling of  auth failures

- frontend/src/supportmanagement/components/ongoing-support-errands/components/support-status-label.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1666
> feat: added solutioncodes for rob

- frontend/public/locales/sv/messages.json
Jira: https://jira.sundsvall.se/browse/DRAKEN-1753
> feat: update messages templates for ks

- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1696
> fix: missing status for phase

- frontend/src/casedata/components/errand/appeal-button.component.tsx
- frontend/src/casedata/components/errand/tabs/decision/casedata-decision-tab.tsx
- frontend/src/casedata/components/errand/tabs/investigation/casedata-investigation-tab.tsx
- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
Jira: https://jira.sundsvall.se/browse/UF-16687
> feat: use loading prop on buttons

- frontend/src/casedata/components/errand/forms/contact-modal.component.tsx
- frontend/src/casedata/components/errand/forms/contact-relation-select.component.tsx
- frontend/src/casedata/components/errand/forms/search-result.component.tsx
- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
- frontend/src/casedata/components/errand/tabs/overview/casedata-contacts.component.tsx
- frontend/src/casedata/interfaces/role.ts
- frontend/src/casedata/services/casedata-stakeholder-service.ts
- frontend/src/supportmanagement/components/new-contacts/support-contact-modal.component.tsx
> fix: display roles correctly for casedata stakeholders

- backend/src/controllers/message.controller.ts
- backend/src/services/message.service.ts
- backend/src/swagger-typescript-api.ts
> feat:update messaging version

- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-priority.component.tsx
- frontend/src/casedata/components/errand/casedata-errand.component.tsx
- frontend/src/casedata/components/ongoing-casedata-errands/components/errands-table.component.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/common/components/layout/layout.component.tsx
- frontend/src/common/components/priority/priority.component.tsx
- frontend/src/supportmanagement/components/ongoing-support-errands/components/supporterrands-table.component.tsx
- frontend/src/supportmanagement/components/supportmanagement-filtering/components/supportmanagement-filter-priority.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1765
> feat: prioritycomponent

- frontend/src/casedata/components/errand/forms/contact-modal.component.tsx
- frontend/src/casedata/components/errand/forms/search-result.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1766
> feat: remove required phone number

- backend/src/services/message.service.ts
> fix: update messaging endpoint

- backend/src/config/api-config.ts
> chore: bump casestatus version

- frontend/src/casedata/components/errand/tabs/overview/casedata-contacts.component.tsx
- frontend/src/casedata/components/errand/tabs/overview/casedata-form.component.tsx
- frontend/src/casedata/components/errand/tabs/overview/casedata-relations-disclosure.component.tsx
- frontend/src/supportmanagement/components/new-contacts/support-contact-search-mode-selector.component.tsx
- frontend/src/supportmanagement/components/new-contacts/support-simplified-contact-form.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1793
> feat: disclosure for casedata

- frontend/src/common/components/layout/layout.component.tsx
- frontend/src/common/components/layout/userMenuGroups.tsx
- frontend/src/common/components/main-errands-sidebar/main-errands-sidebar.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1798
> feat: change avatar to usermenu in main errand sidebar

- frontend/src/casedata/hooks/useSaveCasedataErrand.ts
> fix: issue when saving casedata errand

- frontend/src/casedata/components/errand/tabs/investigation/casedata-investigation-tab.tsx
- frontend/src/casedata/components/errand/tabs/services/casedata-service-form.component.tsx
> fix: document not defined for build + start

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1833
> feat: remove confirm dialog for sending message

- backend/package.json
- backend/yarn.lock
- frontend/package.json
- frontend/src/casedata/components/errand/tabs/investigation/casedata-investigation-tab.tsx
- frontend/yarn.lock
- removed universal-cookie that was unused in frontend.
> chore: dep upgrades

- frontend/src/casedata/components/errand/tabs/overview/casedata-form.component.tsx
- frontend/src/supportmanagement/components/attestation-tab/attestation-tab.component.tsx
- frontend/src/supportmanagement/components/new-contacts/support-contacts.component.tsx
- frontend/src/supportmanagement/components/new-contacts/support-simplified-contact-form.component.tsx
- frontend/src/supportmanagement/components/support-errand/support-tabs-wrapper.tsx
- frontend/src/supportmanagement/components/supportmanagement-filtering/components/supportmanagement-filter-category.component.tsx
- frontend/src/supportmanagement/components/supportmanagement-filtering/components/supportmanagement-filter-type.component.tsx
> Code scan fixes

- frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
> Use ifs instead of ternary

- frontend/cypress/e2e/case-data/mex/errandPage-base-info-tab-mex.cy.ts
- frontend/cypress/e2e/case-data/mex/errandPage-message-tab-mex.cy.ts
- frontend/cypress/e2e/case-data/pt/errandPage-base-info-tab-pt.cy.ts
- frontend/cypress/e2e/case-data/pt/errandPage-decisions-tab-pt.cy.ts
- frontend/cypress/e2e/case-data/pt/errandPage-investigation-tab-pt.cy.ts
- frontend/cypress/e2e/case-data/pt/errandPage-message-tab-pt.cy.ts
- frontend/cypress/e2e/kontaktcenter/errandPage-sidebar-kc.cy.ts
- frontend/cypress/e2e/lop/errandPage-base-info-tab-lop.cy.ts
- frontend/cypress/e2e/lop/errandPage-invoice-tab-lop.cy.ts
- frontend/cypress/e2e/lop/errandPage-sidebar-lop.cy.ts
- frontend/cypress/e2e/lop/oversikt-lop.cy.ts
- frontend/cypress/e2e/lop/register-lop.cy.ts
- frontend/package.json
- frontend/src/app/[locale]/arende/[municipalityId]/[errandNumber]/page.tsx
- frontend/src/app/[locale]/login/page.tsx
- frontend/src/app/[locale]/oversikt/page.tsx
- frontend/src/app/[locale]/registrera/page.tsx
- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-dates.component.tsx
- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-sidebarstatus-selector.component.tsx
- frontend/src/casedata/components/casedata-filtering/components/casedata-filter-tags.component.tsx
- frontend/src/casedata/components/errand/appeal-button.component.tsx
- frontend/src/casedata/components/errand/casedata-errand.component.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/supportmanagement/components/new-contacts/support-simplified-contact-form.component.tsx
- frontend/yarn.lock
> feat: build errors for strict mode

- frontend/src/common/components/layout/userMenuGroups.tsx
- The log out button didn't always work as it should. Sometimes it linked correctly and sometimes not at all.
Jira: https://jira.sundsvall.se/browse/DRAKEN-1838
> fix: fixed logout button link function

- backend/src/app.ts
- frontend/src/casedata/components/errand/phasechanger/phasechanger.component.tsx
- frontend/src/casedata/components/save-button/save-button.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1743
> feat: save errand on phasechange

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1456
> feat: change recipient email address for followup emails

- .github/CODEOWNERS
> fix: Add CODEOWNERS file for github workflows

- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
> fix: recipient email for follow up in sm

- frontend/src/app/api/health/up/route.ts
- frontend/src/middleware.ts
> fix: health check

- frontend/next-env.d.ts
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1849
> fix: Display correct errand status for cd errand when switching page

- backend/src/services/message.service.ts
- frontend/next-env.d.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-1847
> fix: save attachment on message for email

- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
> fix: Nullcheck for status

- frontend/src/supportmanagement/components/ongoing-support-errands/components/support-status-label.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/sidebar-info.component.tsx
> fix: Changing incorrect label eskalerat to överlämnat

- frontend/src/supportmanagement/components/templates/default-escalation-template.ts
- frontend/src/supportmanagement/components/templates/ka-escalation-template.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-1875
> fix: Escalation template updates for new text editor

- frontend/src/casedata/components/errand/tabs/details/casedata-formfield-renderer.tsx
- frontend/src/casedata/services/casedata-extra-parameters-service.ts
- frontend/src/casedata/utils/date-string-handler-utils.ts
- Fixed the bug where the max value was automatically set incorrectly.
- Improved the code with helper functions to make handling of options easier.
Jira: https://jira.sundsvall.se/browse/DRAKEN-1899
> fix: issues when selecting dates in extraparameters

- frontend/src/casedata/components/errand/phasechanger/phasechanger-dialog.component.tsx
- frontend/src/casedata/components/errand/phasechanger/phasechanger.component.tsx
- frontend/src/casedata/components/errand/sidebar/sidebar-info.component.tsx
- frontend/src/casedata/components/errand/tabs/decision/casedata-decision-tab.tsx
- frontend/src/casedata/components/errand/tabs/decision/send-decision-dialog.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1903
> feat: Updated styling for phasechanger dialogs

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1844
> fix: Adjust logic for contact channels for messages

- frontend/next-env.d.ts
- frontend/package.json
- frontend/yarn.lock
> chore: bump next version

- README.md
- backend/src/config/api-config.ts
> fix: bump supportmanagement to 10.7 due to subscription reasons

- frontend/src/config/appconfig.tsx
> fix: build errors ka

- frontend/src/common/services/sanitizer-service.ts
- frontend/src/supportmanagement/components/support-errand-basics-form/support-errand-basics-about-form.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-1913
> fix: Support for link in errand description

- frontend/src/supportmanagement/components/support-errand-basics-form/support-errand-basics-about-form.component.tsx
> fix: set dirty on rich text change

- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
This fix is regarding casedata
> fix: hide contact channel minasidor until release

- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-2091
> feat: fixed issue with message context in texteditor

- frontend/src/casedata/components/errand/casedata-tabs-wrapper.tsx
We had previous multiple disable layers active
Jira: https://jira.sundsvall.se/browse/DRAKEN-2069
> fix: removed one disable level

- backend/.env.kc.example.local
- backend/.env.lop.example.local
- backend/.env.mex.example.local
- backend/.env.msva.example.local
- backend/.env.pt.example.local
- backend/.env.rob.example.local
- backend/src/app.ts
- backend/src/utils/isValidateOrigin.ts
- frontend/next-env.d.ts
> feature: redirect urls  on SAML_SUCCESS_REDIRECT in backend

- frontend/src/common/components/linked-errands-disclosure/relation-tables/relations-to-table.component.tsx
- frontend/src/supportmanagement/services/support-conversation-service.ts
> fix: Imports

- frontend/src/supportmanagement/components/new-contacts/support-contacts.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-2200
> feat: Information text for migrated contact

- backend/src/controllers/supportmanagement/support-errand.controller.ts
- frontend/next-env.d.ts
- frontend/src/casedata/components/errand/tabs/details/casedata-details-tab.tsx
- frontend/src/casedata/components/errand/tabs/messages/rendered-message.component.tsx
- frontend/src/casedata/services/casedata-errand-service.ts
- frontend/src/common/services/helper-service.ts
- frontend/src/common/services/sanitizer-service.ts
- frontend/src/supportmanagement/components/attestation-tab/attestation-invoice-form.component.tsx
- frontend/src/supportmanagement/components/attestation-tab/components/attestations-table.component.tsx
- frontend/src/supportmanagement/components/support-errand-basics-disclosure/support-errand-basics-about-disclosure.component.tsx
- frontend/src/supportmanagement/components/support-errand-basics-form/support-errand-basics-about-form.component.tsx
- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
- frontend/src/supportmanagement/components/support-errand/tabs/messages/rendered-support-message.component.tsx
- frontend/src/supportmanagement/components/templates/escalation-template.ts
- frontend/src/supportmanagement/services/support-errand-service.ts
- frontend/src/supportmanagement/services/support-escalation-service.ts
Jira: https://jira.sundsvall.se/browse/DRAKEN-2211
> feat: updated styling and functionallity for messages and templates

- frontend/src/common/components/sidebar/sidebar.component.tsx
> fix: Sidebar wrapper styling for small screens

- frontend/src/casedata/components/errand/forms/simplified-contact-form.component.tsx
- frontend/src/casedata/components/errand/tabs/messages/message-composer.component.tsx
- frontend/src/casedata/services/casedata-stakeholder-service.ts
- frontend/src/common/components/commonNestedEmailArrayV2.tsx
- frontend/src/common/components/commonNestedPhoneArrayV2.tsx
- frontend/src/common/services/helper-service.ts
- frontend/src/common/utils/phoneNumberFormatter-utils.ts
- frontend/src/supportmanagement/components/support-errand/sidebar/request-internal.component.tsx
- frontend/src/supportmanagement/components/support-message-form/support-message-form.component.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-2235
> feat: new validation logic for phonenumbers

- frontend/cypress/e2e/kontaktcenter/errandPage-message-tab-kc.cy.ts
- frontend/cypress/e2e/lop/errandPage-message-tab-lop.cy.ts
- frontend/package.json
- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
- frontend/yarn.lock
- Downgrade for texteditor to 1.1.0
- Escalation trigger changes for KA
- Build issues related to tests
> fix: texteditor and escalation fixes

- frontend/src/supportmanagement/components/support-errand/sidebar/forward-errand.component.tsx
> fix: temp fix for KA

- frontend/src/common/components/commonNestedPhoneArrayV2.tsx
Jira: https://jira.sundsvall.se/browse/DRAKEN-2274
> fix: phonenumber fix
